Add LotteryConfig as parameter to Executable#execute method
jboss-set/jira-issue-lottery pull request #31
Opened 2023-12-01 14:31 UTC by The-Huginn

2023-12-04 08:16 UTC, xjusko approved these changes

2023-12-06 10:18 UTC, xstefank reviewed
I just don't understand why you need this if you don't use it? Planning something that requires separate PR?

2023-12-07 08:07 UTC, The-Huginn commented
I have updated the PR as I mentioned above

2023-12-08 12:32 UTC, xstefank requested changes

2023-12-08 12:32 UTC, xstefank commented on src/main/java/org/jboss/processing/NewIssueCollector.java
> +        new EveryIssueState(state.issueStates);
why are you creating object that is immediately going to be collected? Do you want to do something with this instance?

2023-12-14 10:27 UTC, xstefank approved these changes

2023-12-14 12:16 UTC, merged