Rename packages under java/main from org.jboss to org.jboss.set
jboss-set/jira-issue-lottery pull request #47
Opened 2024-01-22 09:50 UTC by xjusko

resolves #45

2024-02-14 13:20 UTC, The-Huginn requested changes
I believe pom.xml should have this renamed as well

2024-02-14 18:11 UTC, xjusko commented
You are right, I forgot about that, it should be fixed now.

2024-02-27 14:40 UTC, xstefank approved these changes

2024-02-27 14:40 UTC, xstefank commented
@xjusko needs rebase

2024-02-28 12:00 UTC, xstefank approved these changes

2024-02-28 12:00 UTC, merged