Move jira-issue-lottery.config-file-repo value from application.properties to .env file and set a default for testing.
jboss-set/jira-issue-lottery pull request #66
Opened 2024-02-27 12:57 UTC by xjusko

resolves #49  as the previous PR which included this was closed

2024-02-27 14:47 UTC, xstefank requested changes

2024-02-27 14:47 UTC, xstefank commented on README.md
> +2. Add the value of `%dev.jira-issue-lottery.config-file-repo` in the `.env` file to point to a public repository with a valid config file according to first step in [Configuration section](#configur
Why do you need to move it out of application.properties? If it's environment variable than the naming should be adjusted to make it clear - e.g., THIS_IS_ENV_VAR

2024-02-27 15:16 UTC, The-Huginn approved these changes
LGTM

2024-02-29 16:04 UTC, xstefank approved these changes

2024-02-29 16:04 UTC, merged