Add formatter GitHub action workflow
jboss-set/jira-issue-lottery pull request #78
Opened 2024-03-26 11:10 UTC by The-Huginn

resolves #77

2024-03-26 11:20 UTC, The-Huginn commented
Also deletes empty trailing file from previous PRs

2024-04-30 14:04 UTC, xstefank requested changes

2024-04-30 14:04 UTC, xstefank commented on src/main/java/org/jboss/set/JiraIssueLotteryCommand.java
?

2024-04-30 14:04 UTC, xstefank approved these changes

2024-04-30 14:04 UTC, xstefank commented on src/main/java/org/jboss/set/JiraIssueLotteryCommand.java
ok, I missed the comment

2024-04-30 14:04 UTC, merged