Change new line value from /n to <br> so the email is correctly formtted
jboss-set/jira-issue-lottery pull request #80
Opened 2024-04-08 10:43 UTC by xjusko

resolves #79

2024-04-09 08:22 UTC, The-Huginn requested changes
I think we can also update itemization of issues utilizing unordered list <ul> html tag, which also adds the bullet character. Please see https://www.w3schools.com/tags/tag_li.asp
Also, I might be worth it adding <br> tag into the `PROJECT_LINE`.Thus would be `PROJECT_LINE = "...<br>\n" so it still looks readable in String form.

2024-04-09 08:22 UTC, The-Huginn commented on src/main/java/org/jboss/set/draw/Lottery.java
> +                        .collect(joining("<br>")),
```suggestion
                        .collect(joining("<br>\n")),
```

So the string represantation is still human-readable

2024-04-10 08:01 UTC, The-Huginn approved these changes
Except the suggestion, LGTM

2024-04-10 08:01 UTC, The-Huginn commented on src/main/java/org/jboss/set/draw/Lottery.java
> +        return String.format(EMAIL_BODY, getUsername(email), projectHtml, configFileUrl());
```suggestion
        return EMAIL_BODY.formatted(getUsername(email), projectHtml, configFileUrl());
```

2024-04-10 08:09 UTC, xjusko commented
For the reference, this is how the email will be formatted after the changes.
![image](https://github.com/jboss-set/jira-issue-lottery/assets/73242687/53f97ea3-1d6c-426b-b310-44ef7c9870ec)

2024-06-05 10:30 UTC, merged